#!/usr/bin/env ts-node
/**
 * Apply Module Permissions Script
 * 
 * Automatically applies permissions SQL generated by CLI
 * and assigns to admin role (role_id = 1)
 * 
 * Usage:
 *   npm run script:permissions <module-name> [tenant-slug]
 * 
 * Examples:
 *   npm run script:permissions orders
 *   npm run script:permissions orders tenant_2
 */

import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const moduleName = process.argv[2];
const tenantSlug = process.argv[3] || 'tenant_1';

if (!moduleName) {
  console.error('❌ Error: Module name is required');
  console.log('Usage: npm run script:permissions <module-name> [tenant-slug]');
  console.log('Example: npm run script:permissions orders tenant_1');
  process.exit(1);
}

async function applyPermissions() {
  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
  });

  try {
    console.log(`\n📋 Applying permissions for module: ${moduleName}`);
    console.log(`🏢 Tenant: ${tenantSlug}\n`);

    // 1. Read permissions SQL file
    const sqlFilePath = path.join(
      __dirname,
      '../database/migrations/permissions',
      `${moduleName}-permissions.sql`
    );

    if (!fs.existsSync(sqlFilePath)) {
      console.error(`❌ Permissions SQL file not found: ${sqlFilePath}`);
      console.log('\n💡 Tip: Generate module first using CLI:');
      console.log(`   cd cli && node bin/cms.js generate crud ${moduleName}`);
      process.exit(1);
    }

    let sqlContent = fs.readFileSync(sqlFilePath, 'utf-8');

    // 2. Replace tenant_1 with actual tenant slug
    sqlContent = sqlContent.replace(/tenant_1/g, tenantSlug);

    console.log('📄 SQL content loaded');
    console.log('─'.repeat(50));

    // 3. Execute SQL to insert permissions
    await pool.query(sqlContent);
    console.log('✅ Permissions created successfully');

    // 4. Assign permissions to admin role (role_id = 1)
    const assignQuery = `
      INSERT INTO ${tenantSlug}.role_permissions (role_id, permission_id)
      SELECT 1, id 
      FROM ${tenantSlug}.permissions 
      WHERE resource = $1
      ON CONFLICT DO NOTHING;
    `;

    const result = await pool.query(assignQuery, [moduleName]);
    console.log(`✅ Assigned ${result.rowCount} permissions to admin role`);

    // 5. Show created permissions
    const listQuery = `
      SELECT name, slug, action, description
      FROM ${tenantSlug}.permissions
      WHERE resource = $1
      ORDER BY action;
    `;

    const { rows } = await pool.query(listQuery, [moduleName]);
    
    console.log('\n📝 Created Permissions:');
    console.log('─'.repeat(50));
    rows.forEach(row => {
      console.log(`  • ${row.name} (${row.slug})`);
      console.log(`    ${row.description}`);
    });

    console.log('\n✅ Done! Permissions applied and assigned to admin role.\n');

  } catch (error) {
    console.error('\n❌ Error applying permissions:', error);
    if (error instanceof Error) {
      console.error('Message:', error.message);
    }
    process.exit(1);
  } finally {
    await pool.end();
  }
}

applyPermissions();
