import { Module } from '@nestjs/common';
import { NewsController } from './news.controller';
import { NewsService } from './news.service';
import { NewsRepository } from './news.repository';
import { DatabaseModule } from '../../database/database.module';
import { CaslModule } from '../../core/casl/casl.module';

/**
 * news Module
 * Auto-generated CRUD module
 * 
 * Generated by Module Builder
 * @generated
 */
@Module({
  imports: [
    DatabaseModule,
    CaslModule,
  ],
  controllers: [NewsController],
  providers: [
    NewsService,
    NewsRepository,
  ],
  exports: [
    NewsService,
    NewsRepository,
  ],
})
export class NewsModule {}
