-- Migration: Create news table
-- Generated by Module Builder
-- @generated

CREATE TABLE IF NOT EXISTS news (
  id BIGSERIAL PRIMARY KEY,

  uuid UUID,
  title VARCHAR,
  content TEXT,
  image VARCHAR,
  date VARCHAR,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,

  deleted_at TIMESTAMPTZ,

  -- Unique constraints

  -- Check constraints (placeholder for validations)
  CONSTRAINT news_id_check CHECK (id > 0)
);

-- Indexes
CREATE INDEX idx_news_deleted_at ON news(deleted_at);

CREATE INDEX idx_news_created_at ON news(created_at DESC);


-- Comments
COMMENT ON TABLE news IS 'news';
COMMENT ON COLUMN news.uuid IS 'Uuid';
COMMENT ON COLUMN news.title IS 'Title';
COMMENT ON COLUMN news.content IS 'Content';
COMMENT ON COLUMN news.image IS 'Image';
COMMENT ON COLUMN news.date IS 'Date';
