-- Menu Item Registration for TestItems
-- This file is auto-generated by CLI Generator
-- Apply this to your tenant schema to register menu item
--
-- Usage:
--   psql -U postgres -d platform_cms -v tenant_schema=tenant_demo_company -f this_file.sql
--
-- Or set tenant schema manually:
--   \set tenant_schema 'tenant_demo_company'
--   \i this_file.sql

-- Set search path to tenant schema
SET search_path TO :tenant_schema, public;

-- Insert main menu group if not exists
INSERT INTO menus (
  name,
  slug,
  icon,
  "order",
  is_active,
  created_at,
  updated_at
)
VALUES (
  'Main Menu',
  'main-menu',
  'LayoutDashboard',
  1,
  true,
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO NOTHING;

-- Insert menu item for TestItems
INSERT INTO menu_items (
  menu_id,
  parent_id,
  module_name,
  label,
  url,
  icon,
  required_permission,
  "order",
  is_active,
  created_at,
  updated_at
)
SELECT 
  m.id AS menu_id,
  NULL AS parent_id,
  'test-items' AS module_name,
  'Test items' AS label,
  '/portal/test-items' AS url,
  'Box' AS icon,
  'test-items:read' AS required_permission,
  (SELECT COALESCE(MAX("order"), 0) + 1 FROM menu_items WHERE menu_id = m.id AND parent_id IS NULL AND deleted_at IS NULL) AS "order",
  true AS is_active,
  NOW() AS created_at,
  NOW() AS updated_at
FROM menus m 
WHERE m.slug = 'main-menu'
  AND m.is_active = true
  AND m.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM menu_items 
    WHERE module_name = 'test-items' 
      AND menu_id = m.id
      AND deleted_at IS NULL
  );

-- Insert sub-menu items (CRUD actions)
INSERT INTO menu_items (
  menu_id,
  parent_id,
  module_name,
  label,
  url,
  icon,
  required_permission,
  "order",
  is_active,
  created_at,
  updated_at
)
SELECT 
  m.id AS menu_id,
  parent.id AS parent_id,
  'test-items' AS module_name,
  sub.label,
  sub.url,
  NULL AS icon,
  sub.permission,
  sub."order",
  true AS is_active,
  NOW() AS created_at,
  NOW() AS updated_at
FROM menus m
CROSS JOIN (
  SELECT id FROM menu_items 
  WHERE module_name = 'test-items' 
    AND menu_id = m.id 
    AND parent_id IS NULL
    AND deleted_at IS NULL
  LIMIT 1
) parent
CROSS JOIN (
  SELECT * FROM (VALUES
    ('All Test items', '/portal/test-items', 'test-items:read', 1),
    ('Create Test item', '/portal/test-items/create', 'test-items:create', 2)
  ) AS t(label, url, permission, "order")
) sub
WHERE m.slug = 'main-menu'
  AND m.is_active = true
  AND m.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM menu_items mi
    WHERE mi.module_name = 'test-items'
      AND mi.parent_id = parent.id
      AND mi.url = sub.url
      AND mi.deleted_at IS NULL
  );

-- Success message
DO $$
BEGIN
  RAISE NOTICE '✓ Menu items for TestItems registered successfully!';
  RAISE NOTICE '  - Main menu: /portal/test-items';
  RAISE NOTICE '  - Icon: Box';
  RAISE NOTICE '  - Permission: test-items:read';
  RAISE NOTICE '  - Sub-items: 2 (All Test items, Create Test item)';
END $$;
